import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import { AuthContextProvider } from "@/context/AuthContext";
import { Toaster, resolveValue } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Toaster
            position="bottom-center"
            toastOptions={{
              success: {
                className: "toast-success",
                duration: 3000,
                style: {
                  backgroundColor: "#344054",
                  color: "white",
                },
              },
              error: {
                className: "toast-error",
                duration: 3000,
                style: {
                  backgroundColor: "red",
                  color: "white",
                  minWidth: "max-content",
                },
              },
            }}
          />
          <div className="flex flex-col gap-2">
            <Navbar />
            <div className="w-full max-w-[112rem] mx-auto pt-[5rem]">
              {children}
            </div>
          </div>
        </AuthContextProvider>
      </body>
    </html>
  );
}
